# Generated by Django 3.2.16 on 2022-10-25 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='expense_records.expensetype'),
            preserve_default=False,
        ),
    ]
