# Generated by Django 3.2.16 on 2022-10-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_records', '0002_auto_20221025_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='hasDetails',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TagPerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseDetailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_records.expensedetail')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='expense_records.tag')),
            ],
        ),
        migrations.AddField(
            model_name='expensedetail',
            name='expenseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_records.expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='expense_records.category'),
            preserve_default=False,
        ),
    ]
